market: main_p1.cpp market.cpp worker.cpp blank_trader.cpp
	g++ -std=c++20 main_p1.cpp market.cpp worker.cpp blank_trader.cpp -lpthread -o market

# For part2
trader: main_p2.cpp market.cpp worker_p2.cpp trader.cpp
	g++ -std=c++20 main_p2.cpp market.cpp worker_p2.cpp trader.cpp -lpthread -o trader

